### ISSUE TITLE
Example Error inexportXML 

### ISSUE THREAD

**Issue by titopalladino** [TrimbleSolutionsCorporation/TSOpenAPIExamples#11]
I have an exception error in line 
   Part myPart = myEnum.Current as Part;  ERROR
Se omitió la carga de símbolos para el módulo mscorlib.dll optimizado porque está habilitada la opción Sólo mi código.

The compilation is OK 
Could you help me

**Comment by CarlosHerrero** [comment]
Hello, you can search for topics related to "Just My Code" option in Visual Studio. For example:
https://stackoverflow.com/questions/32048766/what-is-just-my-code
