### ISSUE TITLE
ANY EXAMPLES FOR CREATE CROSS SECTION?

### ISSUE THREAD

**Issue by better319** [TrimbleSolutionsCorporation/TSOpenAPIExamples#12]
ANY EXAMPLES FOR CREATE CROSS SECTION?

**Comment by better319** [comment]
ANY EXAMPLES FOR CREATE CROSS SECTION?

**Comment by better319** [comment]
about Special-shaped cross-section

**Comment by CarlosHerrero** [comment]
Hello,
It is not possible to create new cross sections with Open API. Only import profiles with the CatalogHandler class:
https://developer.tekla.com/tekla-structures/api/28/9102
