### ISSUE TITLE
How to create Assembly

### ISSUE THREAD

**Issue by Tejal-Alai** [TrimbleSolutionsCorporation/TSOpenAPIExamples#13]
I want to create assembly I tried it by 2 ways
1)I have tried to create ArrayList of ModelObjects and then tried to create assembly using Assembly.Add method but its throwing error.

            List<ModelObject> modelObjectsList = new List<ModelObject>();
            Beam beam = new Beam();
            ModelObject modelObject = beam as ModelObject;
            modelObjectsList.Add(modelObject);
            ArrayList arrayListofAssemblables = new ArrayList();
            arrayListofAssemblables.Add(modelObjectsList);
            Assembly assembly = new Assembly();
            assembly.Add(arrayListofAssemblables);
           
2) Passing model object to IAssemblable and then pass it to .Add method but its still throwing error that 'Assemblable is not valid'        
           
            Beam beam = new Beam();
            ModelObject modelObject = beam as ModelObject;
            Assembly assembly = new Assembly();
            IAssemblable assemblable = modelObject as IAssemblable;
            assembly.Add(assemblable);

**Comment by CarlosHerrero** [comment]
Internal code of TeklaStructures creates assembly automatically when a part is inserted.
myPart.Insert();
myPart.GetAssembly(); // returns the assembly created by internal code

**Comment by Tejal-Alai** [comment]
myPart.Insert(); 
this is not working for me as i have to do unit testing of my function which takes assembly as input and while unit testing i can not insert functionality
