### ISSUE TITLE
Operation.CopyObject(Part, oldCoordinate, newCoordinate) Successed, but the CoordinateSystem become null after model.CommitChanges();

### ISSUE THREAD

**Issue by inquick** [TrimbleSolutionsCorporation/TSOpenAPIExamples#14]
I use the code below to copy a part form the selected one.
`private void TestCopyObject()
{
    Picker Picker = new Picker();
    Part Part = Picker.PickObject(Picker.PickObjectEnum.PICK_ONE_PART) as Part;

    var oldCoordinate = Part.GetCoordinateSystem();
    var solid = Part.GetSolid();
    // The old coordinate system uses the model center point of the part as the origin.
    oldCoordinate.Origin = new Point((solid.MinimumPoint.X + solid.MaximumPoint.X) / 2, (solid.MinimumPoint.Y + solid.MaximumPoint.Y) / 2, (solid.MinimumPoint.Z + solid.MaximumPoint.Z) / 2);

    // Calculate the correct AxisY, making sure it is perpendicular to AxisX
    var originalAxisX = oldCoordinate.AxisX;
    var originalAxisY = oldCoordinate.AxisY;
    var newAxisY = originalAxisX.Cross(originalAxisY);
    newAxisY.Normalize(); // To Unit vector
    var newCoordinate = new T3D.CoordinateSystem
    {
        AxisX = new T3D.Vector(1, 0, 0),
        AxisY = newAxisY
    };

    Model model = new Model();

    var newPart = Operation.CopyObject(Part, oldCoordinate, newCoordinate) as Part;

    var newPartCoordinate = newPart.GetCoordinateSystem();
    if (newPartCoordinate != null)
    {
        Console.WriteLine($"The newPartCoordinate origin:{newPartCoordinate.Origin}, AxisX:{newPartCoordinate.AxisX},AxisY:{newPartCoordinate.AxisY}");
    }

    model.CommitChanges();

    newPartCoordinate = newPart.GetCoordinateSystem();
    if (newPartCoordinate == null)
    {
        Console.WriteLine("The part coppied, has no CoordinateSystem.");
    }
    else
    {
        Console.WriteLine("The part coppied, has correct CoordinateSystem.");
    }
}`

Most of the time it is correct, but sometimes the copied part does not have a coordinate system.
I found that it copied the Part and its children，Does it also copied something else that causes the coordinate system to be abnormal after committing?Why did my copy fail?

![image](https://github.com/TrimbleSolutionsCorporation/TSOpenAPIExamples/assets/23495354/59dd6315-e9e5-4add-9634-3850f8519973)
![image](https://github.com/TrimbleSolutionsCorporation/TSOpenAPIExamples/assets/23495354/7b8ce7a2-4be5-4085-9b02-9e82e4da297b)
![image](https://github.com/TrimbleSolutionsCorporation/TSOpenAPIExamples/assets/23495354/c99ef5ef-1333-4b02-a861-6cc6a1db8686)

I use the 2021 API

**Comment by CarlosHerrero** [comment]
Hello,
Please, use Tekla Open API Discussion Forum to ask general questions about writing code for Tekla Structures: https://forum.tekla.com/forum/269-api-general-discussions/
Issues here should be about problems with the repository itself. For example, if a branch is missing, problems when cloning, etc.
