### ISSUE TITLE
How to get the model folder location?

### ISSUE THREAD

**Issue by martin9020** [TrimbleSolutionsCorporation/TSOpenAPIExamples#16]
1) I am trying to get the file path location of attributes in the model?
2) can i get the location for XS_Firm folder from the settings?

**Comment by Choochoote** [comment]
Hi Martin,
I Guess modelInfo class could help for model path

https://developer.tekla.com/doc/tekla-structures/2024/model-info-class-27868

And also, TeklaStructuresSettings class for advanced option XS_FIRM

https://developer.tekla.com/doc/tekla-structures/2024/tekla-structures-settings-class-20492

Anne

**Comment by martin9020** [comment]
string xsFirmPath = "";
TeklaStructuresSettings.GetAdvancedOption("XS_FIRM", ref string xsFirmPath)
this is now correctly getting the firm folder in the string "xsFirmPath "

string modelFolder = MyModel.GetInfo().ModelPath;    
and this as modelfolder string

Thanks Anne
