### ISSUE TITLE
Antivirus conflict?

### ISSUE THREAD

**Issue by martin9020** [TrimbleSolutionsCorporation/TSOpenAPIExamples#17]
Just a question, as I want at some point the app I am creating at home to be used at work.
And at work we value the security for various reasons, and a file that is beeing blocked, is not OK.
When I compile with VS2022 the antivirus is seeking to block the Exercise#.exe  files.
I am using N** Antivirus and when N** is off the Microsoft Windows Security also finds these files for "suspicious" files.
My question is.. what is causing this problem, and is there a way to remove or add something to fix it?
Is it only with me?

**Comment by CarlosHerrero** [comment]
Folders where code is stored and project compiled must be added to antivirus exclusion list.
