### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by frankberns19711015** [TrimbleSolutionsCorporation/TSOpenAPIExamples#5]
On open the example code FormPlugin, all references are issued by Exclamation mark!
 
I uninstalled Tekla API and installed de tekla API exclamatin mark issu not solved
**_path_** en **_version_** on de propeties are not filled. 

![API 1 Licotec](https://user-images.githubusercontent.com/27008068/54903997-8f465180-4edd-11e9-99de-14e0353f9954.png)

regards Frank  (Licotec)

**Comment by CarlosHerrero** [comment]
Hello,

Did you try opening Examples.sln file instead of FormPlugin.csproj file?

**Comment by frankberns19711015** [comment]
Examples.sln same result.

after i installed 2019 Tekla API (NuGet) it works no conficts
