### ISSUE TITLE
Can't create WPF Plugin from scratch

### ISSUE THREAD

**Issue by KuraiAndras** [TrimbleSolutionsCorporation/TSOpenAPIExamples#7]
I am able to create a new froms plugin, but I can't get a wpf plugin to build.

Steps to reproduce:

1. Create new project .Net Framework Class library, .net framewrok 4.7.2
2. Add <ProjectTypeGuids>{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids> to csproj to let Visual Studio know this is WPF
3. Add Tekla Open API nuget to csproj
4. Add wpf references to csproj: PresentationCore, PresentationFramework, WindowsBase, System.Xaml
5. Add WPF Window (xaml + xaml.cs)
6. Inherit from PluginWindowBase

When I build I get the following error:
Error CS0234 The type or namespace name 'Structures' does not exist in the namespace 'My.NameSpace.Tekla' (are you missing an assembly reference?)

Do you know what causes this or can you provide a step-by-step guide to creating a WPF plugin? 

https://developer.tekla.com/tekla-structures/documentation/tekla-open-api-ui-design-wpf

This guide details the creation of the plugin, but not the project creation, or the needed references

**Comment by JaanaHannila** [comment]
Have you checked [Get started guide](https://developer.tekla.com/tekla-structures/documentation/get-started-tekla-structures-open-api) in Tekla Developer Center? It explains how to create a new Microsoft Visual Studio project and how to prepare your setup.

**Comment by KuraiAndras** [comment]
It seems that i have found the problem. It seems like if my assembly name has the word Tekla in it won't build. Removing .Tekla from my assembly name resolved the issue with building the project

Also thanks for your answer, but the getting started guide only explains creating a standalone application that connects to TeklaStructures. (Not a plugin, and all the examples provided on that link show Windows Forms UI, not WPF)
